apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env-config
  namespace: workshop-dev
data:
  HOSTNAME: ''
  PORT: '1323'
  FLAG_IS_LIMIT_MAX_SPEND_ON_CREATE: 'true'
  DB_CONNECTION: 'postgresql://group-3:group-3-pass@database-1.c7bdavepehea.ap-southeast-1.rds.amazonaws.com/group-3-dev'
  